# Generated by Django 5.1.1 on 2024-11-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jah_Accounts', '0002_order_quantity_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Quantity',
            new_name='Quantity_kgs',
        ),
    ]
