# Generated by Django 5.1.3 on 2024-12-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jah_Accounts', '0003_rename_quantity_order_quantity_kgs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Quantity_kgs',
            new_name='Quantity',
        ),
    ]
