# Generated by Django 5.1.3 on 2025-01-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jah_Accounts', '0004_rename_quantity_kgs_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out_for_Delivery', 'Out_for_Delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
