# Generated by Django 5.1.3 on 2025-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jah_Accounts', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurement',
            field=models.CharField(choices=[('Kgs', 'Kgs'), ('Tins', 'Tins')], max_length=200, null=True),
        ),
    ]
