# Generated by Django 5.1.3 on 2025-01-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jah_Accounts', '0007_order_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='measurement',
            new_name='units',
        ),
    ]
